site_name: My Docs
theme: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src/data_deidentifier]
          options:
            docstring_style: google
            members_order: source
            show_source: false
            merge_init_into_class: true
            docstring_options:
              ignore_init_summary: true
            extensions:
              - griffe_inherited_docstrings
